---
title: "Activity 4"
author: "Alyssa Andrichik"
date: "11/20/2019"
output: pdf_document
---
```{r echo = FALSE}
data <- read.csv("https://raw.githubusercontent.com/stat-learning/course-materials/master/data/handwritten.csv")

plot_letter <- function(x, hasletter = TRUE) {
  if(hasletter) {
    a <- as.numeric(x[, -1])
  }else{a <- as.numeric(x)}
  m <- matrix(a, nrow = 8, byrow = TRUE)
  m <- t(apply(m, 2, rev)) # rotate matrix
  par(mar = rep(0, 4))
  image(m, axes = FALSE, col = rev(grey(seq(0, 1, length = 256)))) #this should be a divergent palette
  box()
}

pc_grid <- function(pca, data) {
  d <- data
  grid_points <- as.matrix(expand.grid(seq(-1.5, 1.5, length.out = 5), 
                                       seq(-1.5, 1.5, length.out = 5)))
  pc_points <- pca$x[, 1:2]
  nearest_ind <- rep(NA, nrow(grid_points))
  for(i in 1:nrow(grid_points)) {
    gp <- matrix(rep(grid_points[i, ], nrow(pc_points)), 
                 ncol = 2, byrow = TRUE)
    nearest_ind[i] <- which.min(rowSums((pc_points - gp)^2))
  }
  nearest_grid <- data.frame(d[nearest_ind, ])
  par(mfrow = c(5, 5))
  regrid <- c(21:25, 16:20, 11:15, 6:10, 1:5)
  for(i in regrid) {
    plot_letter(nearest_grid[i, ])
  }
}
```

1) Rows are letters, or the observations. Columns seem to be aspects of the observations, or the variables.

2)
```{r}
#Data Set Containing Only Obs of "a"
library(dplyr)
Adata <- data %>%
  filter(letter == "a")
```

3)
```{r}
plot_letter(Adata[5,], hasletter = TRUE)
plot_letter(Adata[7,], hasletter = TRUE)
plot_letter(Adata[12,], hasletter = TRUE)
```

4)
```{r}
#Mean of A
amean <- colSums(Adata[, -1]/nrow(Adata))
amean
plot_letter(amean, hasletter = FALSE)
```

```{r echo = FALSE, fig.height=6.5, fig.width = 6.5, fig.align='center'}
#Scatter Plot
pca1 <- prcomp(Adata[, -1], scale = TRUE)
library(ggplot2)
library(ggrepel)
d <- as.data.frame(pca1$x)

p1 <- ggplot(d, aes(x = PC1, y = PC2)) +
  geom_point(size = 1, alpha = .1) +
  xlim(c(-3, 3)) +
  theme_bw(base_size = 18)
p1
```

```{r echo = FALSE, fig.align="center", fig.height = 5.5, fig.width=7}
#Scree Plot
d2 <- data.frame(PC = 1:64,
                PVE = pca1$sdev^2 / sum(pca1$sdev^2))
ggplot(d2, aes(x = PC, y = PVE)) +
  geom_line() + 
  geom_point() +
  theme_bw(base_size = 18)
```

```{r}
pc_grid(pca1, Adata)
```

```{r}
plot_letter(pca1$rotation[, 1], hasletter = FALSE)
plot_letter(pca1$rotation[, 2], hasletter = FALSE)
```

```{r}
a_mean <- colMeans(Adata[ , -1])
phi <- pca1$rotation
z <- pca1$x
ncomp <- 60
x_star1 <- a_mean + z[1, 1:ncomp] %*% t(phi[, 1:ncomp])
x_star2 <- a_mean + z[2, 1:ncomp] %*% t(phi[, 1:ncomp])
x_star1
x_star2
```